server:
  port: 8189
  servlet:
    context-path: /market-core
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:  jdbc:postgresql://localhost:5433/market
    username: market
    password: singularitypassword
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: false

  integrations:
    cart-service:
      url: http://localhost:8190/market-cart/
      connect-timeout: 5000
      read-timeout: 10000
      write-timeout: 5000